# Generated by Django 4.1.3 on 2022-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='proje resmi'),
        ),
    ]
